### PR TITLE
Update submodule

### PR DESCRIPTION
**Pull request by oldskool**
Update submodule reference to latest commit

### CODE REVIEW

**Comment by franzliedke** [comment]
Hmm, already conflicting. For now, it's best if you always run `git pull` inside the core directory yourself. 

We need to find the best workflow here. When do we update the submodule? /cc @tobscure

**Comment by tobscure** [comment]
@franzliedke Sorry if I'm forgetting something obvious, but do we really need a submodule/studio for people to contribute to core? I imagine people could:

- git clone flarum/flarum
- composer install
- add their git remote in vendor/flarum/core, branch, commit, send PRs

Same with existing extensions.

studio is definitely useful for creating new extensions that don't yet exist on packagist, but what's the benefit for existing ones?

**Comment by franzliedke** [comment]
Yeah, I hadn't noticed your changes when I made that comment. It's fine. (Although I still don't like developing in the vendor folder...)

**Comment by oldskool** [comment]
Ew, no don't develop in the vendor folder! One composer install/update and you could be toast (although Composer warns you about overwriting any local changes). I ended up setting the origin remote branch to my fork instead of the "upstream" `flarum/core`. I'll just have to keep an eye on my fork and keep it up-to-date myself.

**Comment by franzliedke** [comment]
Yeah, I'm keen to investigate how to make that kind of stuff easier with Studio. But right now, it doesn't help much in such a situation, yes.

**Pull request closed without merging**
