### PR TITLE
Allowing access only to index.php, admin.php, api.php and assets folder

### PR DESCRIPTION
**Pull request by terokorp**
Now its changed that way as @tobscure told at #27
Also, disabled autoindex

### CODE REVIEW

**Comment by franzliedke** [comment]
Awesome, thanks a lot!

**Comment by tobscure** [comment]
@terokorp This isn't working for me. This part:

```
<IfModule mod_authz_host.c>
  Require all granted
</IfModule>
```

is causing an Internal Server Error ("The server encountered an internal error or misconfiguration and was unable to complete your request") when I visit the forum's directory. If I remove that part, it works OK, with all non-admin/api/assets requests being rewritten to index.php.

Also, on second thoughts, a blacklist might actually be better, because people might want to drop other files into their forum's root (e.g. favicon, an index.html while they're doing maintenance, some random files they want to be downloadable) and expect them to be accessible.

So I think we should blacklist:

* Any file starting with `.`
* composer.json
* composer.lock
* extensions/
* flarum
* scripts/
* storage/
* Vagrantfile
* vendor/

Do you think this is a good approach @franzliedke?

**Comment by tobscure** [comment]
Apache 2.2.29. Inspecting logs, I'm getting:

```
configuration error:  couldn't perform authentication. AuthType not set!: /flarum/
```

Should we be using an `IfVersion` check instead of `IfModule`? http://stackoverflow.com/a/26029761

**Comment by terokorp** [comment]
@tobscure I think I made mistake on those IfModule lines. Can you try to change mod_authz_host.c lines to mod_authz_core.c and test with apache2.2, I can't test it because all my servers already runs 2.4

**Pull request merged**
