### PR TITLE
Add robots.txt to disallow nojs pages

### PR DESCRIPTION
**Pull request by sijad**
fixes flarum/core#912

### CODE REVIEW

**Comment by sijad** [comment]
please merge with caution, it may break something else
source: http://stackoverflow.com/a/30036604/4774039

**Comment by franzliedke** [comment]
IMO, we should do this using the [robots meta tag or header](https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag).

That should be easier to apply as a generic solution, and works even [if Flarum is installed in a subdirectory](https://github.com/flarum/core/issues/912#issuecomment-205151142).

@sijad Are you interested in fixing this directly in flarum/core? It would either need to be done in a middleware, or in `WebAppView`, which [already has a line dealing with `nojs`](https://github.com/flarum/core/blob/fcfc1b2a37e704955093f8d6082d327765dbef9c/src/Http/WebApp/WebAppView.php#L323).

**Comment by franzliedke** [comment]
I think I slightly tend towards the middleware solution - does anyone see downsides?

**Comment by sijad** [comment]
yes, that's a better solution

**Pull request closed without merging**
