### PR TITLE
Add RewriteBase to .htaccess

### PR DESCRIPTION
**Pull request by mkibiger**
can trigger an issue in apache. gives 500 errors

### CODE REVIEW

**Comment by franzliedke** [comment]
Does this fix any issues for you? If so, please describe them in detail. :)

**Comment by mkibiger** [comment]
Yes for me it fixed a 500 Server error. 

This is error message.
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>

**Comment by franzliedke** [comment]
Can you post the error message itself from the server's error log?

**Comment by tobscure** [comment]
Closing due to inactivity. @mkibiger we appreciate the PR but we need to know exactly what/how/why it solves an issue before we can merge it :)

**Pull request closed without merging**
