### PR TITLE
nginx rule to prevent access to sensitive files

### PR DESCRIPTION
**Pull request by clarkwinkelmann**
Add a suggested rule that does the same as the suggested rule in .htaccess.

This is the rule I've been using in production on my sites that are not using a public folder.

We should also update the documentation to suggest un-commentating those lines, just like we do for Apache.

### CODE REVIEW

**Comment by clarkwinkelmann** [comment]
I just noticed my rules do not include `.git` whereas the htaccess rules do. Should I add it ? No one will have the Flarum skeleton installed via git in production though :thinking:

**Comment by JoshyPHP** [comment]
> No one will have the Flarum skeleton installed via git in production though

Famous last words. :laughing: I would consider blocking everything that starts with a `.` just in case.

**Comment by clarkwinkelmann** [comment]
> I would consider blocking everything that starts with a . just in case.

I fear this might clash with some other scripts that rely on `.well-known` folders for example.

If we add something, we should also add it to the htaccess to stay consistent.

**Comment by luceos** [comment]
Please add `auth.json` as per discussion on Discord. I would also add `.git` but yeah not sure about the rest. Blocking `.well-known` would be an issue for regular user scenarios.

**Comment by clarkwinkelmann** [comment]
Done! (and tested the new rule line on my server)

**Pull request merged**
