### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by luceos** [comment]
Please create PR's with meaningful subjects and a body that clarifies why the PR is happening, what purpose it has and what we can do with it. Thank you for being a valuable contributor in our ecosystem.

https://betterprogramming.pub/how-to-make-a-perfect-pull-request-3578fb4c112

**Comment by Justman10000** [comment]
Could one wait before closing this? Otherwise I'll do a shit! And what is that good for? Hmm, let me think! IT'S A DOCKERFILE!

**Comment by Justman10000** [comment]
I'm so fed up with how my work is being treated!

**Comment by luceos** [comment]
I'm sorry @Justman10000 that you feel this way. 

A good PR will explain the reasoning behind the PR. For instance the reasoning why `.htaccess`, `index.php` and `site.php` had to be pulled in from an outside source. Asking us to open each and every one of those links, while trying to guess why this happens isn't a great way of contributing to open source. You are demanding us to invest a fair amount of time for things you could have easily provide inside a decent PR description. Delegating this effort to the maintainers, who in the end have to maintain what you contributed indefinitely isn't appreciated. That is why I closed the PR.

**Comment by Justman10000** [comment]
The files are drawn extra because the actual ones have to be replaced! In the Dockerfile I move everything from `public` to Flarum's root directory! The files have to be adjusted accordingly...

**Comment by davwheat** [comment]
We'd rather not add a Dockerfile directly to this repo just yet. I think the way we'd rather go is a full Docker Compose setup, on including a DB image too as a separate container.

In addition, the recommended way to install Flarum is by keeping the `public` directory and changing your webroot instead. I wouldn't feel comfortable advertising this as one of our official installation methods.

**Comment by Justman10000** [comment]
> We'd rather not add a Dockerfile directly to this repo just yet. I think the way we'd rather go is a full Docker Compose setup, on including a DB image too as a separate container.
> 
> In addition, the recommended way to install Flarum is by keeping the `public` directory and changing your webroot instead. I wouldn't feel comfortable advertising this as one of our official installation methods.

I see, then I adjust my image like this... I've also thought about a docker-compose

**Comment by Justman10000** [comment]
@luceos @davwheat

Have now programmed this to use the public folder, also made a docker-compose.yml! Both work!

**Comment by tankerkiller125** [comment]
I would not be comfortable with the replacement of the sources file. I don't understand the need for that at all. I do understand adding the php source, but not replacing the system default entirely.

**Comment by Justman10000** [comment]
?

**Comment by Justman10000** [comment]
What source file?

**Comment by luceos** [comment]
I am going to lock this discussion as I only sense frustration and we aren't going to move forward with this pull request. As @davwheat pointed out we will very likely introduce docker into our skeleton at some point, but it is very unlikely this can be contributed by an outside contributor due to the strict requirements we have as a team.

**Pull request closed without merging**
