### PR TITLE
Added docker-compose, dockerfile for custom fpm and nginx config

### PR DESCRIPTION
**Pull request by nadi106**
Having docker, docker compose installed, use:
`docker-compose up -d`
And have a Flarum server instantly available at `localhost:8080`

### CODE REVIEW

**Comment by nadi106** [comment]
Before running make sure to install dependencies:
(linux) `docker run --rm -it -v $PWD:/app composer install`
(windows) `docker run --rm -it -v ${pwd}:/app composer install`
(instructions taken from [composer at docker hub](https://hub.docker.com/_/composer))

**Comment by akiross** [comment]
[This is related](https://github.com/akiross/flarum-podman), if you care about [podman](https://podman.io/) as a docker alternative.

**Comment by franzliedke** [comment]
Thank you very much for the proposal! We currently do not have the capacity to maintain an official Docker image, so I don't want to accept this at this time. :confused: 

For the time being, I can recommend taking a look at one of the community-maintained alternatives, especially [mondediefr/docker-flarum](https://github.com/mondediefr/docker-flarum).

**Comment by nadi106** [comment]
Hi @franzliedke, I understand your restrictions. Though I just want to point out that my solution splits the docker images into three services, instead of two (php, nginx and mariaDB are separate). You can read more in [my post on flarum](https://discuss.flarum.org/d/22011-flarum-on-docker).

**Pull request closed without merging**
